modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="forgivingvoid"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
displayTest="NONE"
logoFile="forgivingvoid.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "forgivingvoid.mixins.json"
[[mixins]]
config = "forgivingvoid.neoforge.mixins.json"
[[dependencies.forgivingvoid]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.forgivingvoid]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.forgivingvoid]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
